version: '3.7'
services:
  idsvr:
    image: curity.azurecr.io/curity/idsvr:latest
    container_name: idsvr
    ports:
    - "6749:6749"
    - "8443:8443"
    environment:
      PASSWORD: Passw0rd1! ##admin user password
      LOGGING_LEVEL: DEBUG
    networks:
      curity:
        aliases:
          - 'sgnl-kong-tutorial-idsvr'
  kong:
    build: ./kong-image
    container_name: kong
    volumes:
      - ${SGNL_KONG_VOLUME_BASE_PATH:-.}/kong-image/configuration/:/usr/local/kong/declarative:/usr/local/share/lua/5.1/kong/plugins/
    ports:
     - "8000:8000"
     - "8001:8001"
     - "8442:8443"
     - "8444:8444"
    environment:
     - KONG_DATABASE=off
     - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
     - KONG_PLUGINS=bundled,phantom-token,sgnlplugin
     - KONG_NGINX_HTTP_LUA_SHARED_DICT=phantom-token 10m
     - KONG_LOG_LEVEL=debug
     - KONG_LUA_PACKAGE_PATH=/usr/local/share/lua/5.1/kong/plugins/sgnlplugin/?.lua
     - KONG_PROXY_ACCESS_LOG=/dev/stdout
     - KONG_ADMIN_ACCESS_LOG=/dev/stdout
     - KONG_PROXY_ERROR_LOG=/dev/stderr
     - KONG_ADMIN_ERROR_LOG=/dev/stderr
     - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
     - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    networks:
      curity:
        aliases:
          - 'sgnl-kong-tutorial-kong'
  api:
    build: ./api
    ports: 
      - "8080:8080"
    container_name: api
    hostname: api
    volumes: 
      - ${SGNL_KONG_VOLUME_BASE_PATH:-.}/api/server/data/:/app/data
    networks:
      curity:
        aliases:
          - 'sgnl-kong-tutorial-api'
networks:
  default:
      name: 'curity'
  curity:
    external: false

